steps:
  - label: ":lint-roller: Pre-commit"
    agents:
      queue: hetzner
    command: |
      set -euo pipefail

      . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
      export NIXPKGS_ALLOW_UNFREE=1
      export NIX_CONFIG="extra-experimental-features = nix-command flakes"

      nix develop --impure --command bash -c '
        pre-commit run --all-files
      '
    notify:
      - github_commit_status:
          context: "buildkite/pre-commit"
    timeout_in_minutes: 10

  - label: ":hammer: Build and Test"
    agents:
      queue: hetzner
    secrets:
      - CPP_SUITE_TOKEN
    command: |
      set -euo pipefail

      . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
      export NIXPKGS_ALLOW_UNFREE=1
      export NIX_CONFIG="extra-experimental-features = nix-command flakes"

      nix develop --impure --command bash -c '
        cd server
        mkdir -p build-debug
        cd build-debug
        cmake -DCMAKE_BUILD_TYPE=Debug -G Ninja ..
        ninja
      '

      nix develop --impure --command bash -c '
        cd server/build-debug
        ctest --output-on-failure -j$(nproc) --output-junit test-results.xml
      '
    artifact_paths:
      - "server/build-debug/test-results.xml"
    plugins:
      - test-collector#v1.10.2:
          files: "server/build-debug/test-results.xml"
          format: "junit"
          api-token-env-name: "CPP_SUITE_TOKEN"
    notify:
      - github_commit_status:
          context: "buildkite/build-and-test"
    timeout_in_minutes: 30
