steps:
  - label: ":hammer: Build and Test"
    command: |
      set -euo pipefail

      curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install linux --init none --no-confirm
      . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh

      export NIXPKGS_ALLOW_UNFREE=1

      nix develop --impure --command bash -c '
        cd server
        mkdir -p build-debug
        cd build-debug
        cmake -DCMAKE_BUILD_TYPE=Debug -G Ninja ..
        ninja
      '

      nix develop --impure --command bash -c '
        cd server/build-debug
        ctest --output-on-failure -j$(nproc) --output-junit test-results.xml
      '
    artifact_paths:
      - "server/build-debug/test-results.xml"
    timeout_in_minutes: 30

  - wait: ~
    continue_on_failure: true

  - label: ":junit: Annotate test results"
    plugins:
      - junit-annotate#v2.4.1:
          artifacts: "server/build-debug/test-results.xml"
