problem_spec_id = "munich-bahn-202608-w1"
gtfs_source_id = "munich"
target_stops_id = "munich-ubahn-202608"
title = "walk 1m/s, full network"
sync = true

max_walking_distance = 500
walking_speed = 1

start_service_date = "20260921"
